### PR TITLE
Running lean

### PR DESCRIPTION
**Pull request by MQin15**

### CODE REVIEW

**Comment by MQin15** [comment]
@lawsonanderson Awesome summary. Managing technology is complete different between a corporation and a startup. Nice! The link is helpful!

**Comment by abigailcstone** [comment]
@lawsonanderson agreed with @MQin15! One interesting thing to consider around the concept of an MVP is that the same idea does not hold true for combination hardware-software startups. Out here in SF at Y-Combinator there is a lot of buzz about BoltVC, the Boston-based hardware-focused VC firm that just announced a partnership with YC. For hardware, you really have to nail it on the first try, as the consumer is not going to want to purchase the product multiple times with each update. For instance, Nest has been slammed for creating  a horrible smoke detector, and has turned away many customers and created opportunities for its competiton to step in. Food for thought! :+1:

**Comment by jenadeng** [comment]
@lawsonanderson Cowabunga! Awesome post. I personally don't understand what "convex dollars" means but I'm not very English literate. However, great summary of the takeaways from the specifying software segment and insights into how to efficiently develop a product.

**Comment by jenadeng** [comment]
Also :+1:

**Comment by CKnaupp15** [comment]
@lawsonanderson Great post and call to action - makes me want to start a lean startup right away. I particularly enjoy the quote from the website you provided a link to: “Lean Startup isn't about being cheap [but is about] being less wasteful and still doing things that are big.” Thanks! :+1:

**Comment by oscar14** [comment]
Related to Lean, the Concierge MVP concept was a real shocker.  Selling a service before you have the machine ready to deliver it?!  It must be true what we learned in class: It is possible to code just about anything. Perhaps you'd like to include mention of Concierge in your summary. :+1:

**Comment by lawsonanderson** [comment]
Thanks for the suggestion @oscar14 , I have added mention of the Concierge MVP per your request!

**Pull request merged**
