### PR TITLE
Create Databases.md

### PR DESCRIPTION
**Pull request by abigailcstone**
@jenadeng @oscar14 @lawsonanderson @CKnaupp15 @MQin15 Hopefully this works--Would love to hear what you guys think!

### CODE REVIEW

**Comment by jenadeng** [comment]
@abigailcstone Thanks for updating the picture illustrating how databases worked although I did like the :smile_cat: picture as well. I thought your summary on databases was very thorough and helpful for people who did not know anything about databases (like myself!). I'm curious to see how the NuSQL databases will evolve from here.
:+1:

**Comment by lawsonanderson** [comment]
Thanks @abigailcstone !  This is a really helpful summary about database types and I am sure that I will reference it before meetings with the engineering/digital team in my next job, as I know that databases are heavily used in their revenue management system! :+1:

**Comment by CKnaupp15** [comment]
@abigailcstone This is great! It helps me to review this summary to better understand the commonalities and differences between relational and not-so-relational databases. Thank you :+1:

**Comment by MQin15** [comment]
@abigailcstone I enjoyed learning about data base as well and impressed by how powerful the new technologies service business purposes! :+1:

**Pull request merged**
