### PR TITLE
Managing people

### PR DESCRIPTION
**Pull request by jenadeng**
Hi team, please re-post your comments to this pull request! @lawsonanderson @abigailcstone @jenadeng @MQin15 @CKnaupp15

### CODE REVIEW

**Comment by jenadeng** [comment]
@oscar14 very insightful summary of your learnings. Programmers are people too! Another thing I took away was the importance of finding people who are passionate about their work because passion can't be taught or faked. :open_hands:

:+1:

**Comment by lawsonanderson** [comment]
Thanks so much @oscar14 for such a well-written and insightful summary here. This is a very important topic for all of us as future managers. Empathy is crucial! :+1:

**Comment by CKnaupp15** [comment]
@oscar14 Thank you for the great lesson learned on how to manage programmers/people! Indeed, software developers are people, too! And asking questions for understanding is always super-important. Very insightful.
That dog picture though, why not include some grumpy cat? ;)
:+1:

**Comment by abigailcstone** [comment]
Very good point about the metaphor--I was also surprised. Also true about github...and that programmers are people too! :+1:

**Comment by jenadeng** [comment]
Posting on behalf of @MQin15 

@oscar14 I like how you also provide the link to purchase the book. So many books I would like to read after this class. :+1:

**Pull request merged**
