### PR TITLE
Website vs app

### PR DESCRIPTION
**Pull request by jenadeng**
Comment on website vs app? @lawsonanderson @abigailcstone @oscar14 @MQin15 @jenadeng

### CODE REVIEW

**Comment by jenadeng** [comment]
@CKnaupp15 very clear and concise summary of the advantages between a :computer: versus :iphone: ! The graphic was super helpful in highlighting the difference between the two. A note about which type of business should start with what might be helpful as a follow-up post.

:+1:

**Comment by abigailcstone** [comment]
Thanks so much for this! I also found it quite helpful. I'm actually at the URX office at the moment and they are all about facilitating interactions between apps and from web browsers to apps through their mobile app index and deeplinks. With more native apps, I'm excited to see new technologies emerge to allow them to "break out of their sandboxes." :+1:

**Comment by lawsonanderson** [comment]
@CKnaupp15 Thanks so much for this excellent summary of what I thought was one of the most interesting topics we discussed in class. This decision is relevant for nearly all entrepreneurs these days and your summary (plus the excellent graphic) will serve as a fantastic resource to refer back to in the future :+1:

**Comment by MQin15** [comment]
@CKnaupp15 This is definitely one of the most useful lesson!! :+1:

**Pull request merged**
