### PR TITLE
Create KANBAN-See Board.MD

### PR DESCRIPTION
**Pull request by MQin15**
Please provide feedback: @jenadeng, @oscar14, @abigailcstone, @mqin15, @cknaupp15. Also give me a :+1:

### CODE REVIEW

**Comment by MQin15** [comment]
Please provide feedback: @jenadeng, @oscar14, @abigailcstone, @mqin15, @cknaupp15. Also. please give me a :+1:

**Comment by lawsonanderson** [comment]
@MQin15 Wow, what a fancy picture! Where can I read even more on this topic?  Super cool! :+1:

**Comment by abigailcstone** [comment]
@MQin15 This is excellent! I, too, love the kanban board concept. We learned about this at a timely moment for me as a first year as we just covered the Toyota Production System in Operations Management, which the concept of kanban is included in. Thank you! :+1:

**Comment by jenadeng** [comment]
@MQin15 love the graphic. Very representative of the concepts we learned in class, but it looks like a very complicated process. Good thing the text explains the four phases of "to do", "design", "development", and "done". Do you think a Kanban board that is simpler would be more effective in practice? :+1: :+1: from me!

**Comment by MQin15** [comment]
@jenadeng Thank you! I think the KANBAN board should be designed based on specific situation. Simpler should be more effective ideally, but in a complex manufacture process or a multi stage supply chain, a few columns might not satisfy the needs. But agreed, no need to make it more complex than it needs to be!

**Comment by MQin15** [comment]
@lawsonanderson Thank you! Here is a link http://en.wikipedia.org/wiki/Kanban and the Chinese Name of KANBAN is 看板.

**Comment by oscar14** [comment]
Good summary. To help bring this to life further, do you want to add in the discussion of next steps implied by the picture?  (What we discussed on the last repo.)  :+1:

**Comment by CKnaupp15** [comment]
@MQin15 Great post! And the picture is very helpful, too. I love Kanban as visualizes for the whole team where they stand and allows everyone to develop a feeling of a healthy pattern, and spot the bottlenecks. Great link to the Chinese Name of KANBAN, would be an awesome addition to the post!
:+1:

**Pull request merged**
