### PR TITLE
Create tips-to-successfully-interviewing-a-developer.md

### PR DESCRIPTION
**Pull request by jenadeng**
Feedback on Tips to Successfully Interview a Developer?  @abigailcstone @lawsonanderson @oscar14 @MQin15 @CKnaupp15

### CODE REVIEW

**Comment by oscar14** [comment]
Thanks for a good overview of how to screen for good coders to hire.  Your section reminds me of the shift in skillset and mindset that a scientist makes when they become a management consultant: Focus on big picture, Focus on what can be done, Structure the big picture, Prioritize the things that need doing, and most importantly Communicate.  Also I like that you embedded a GIF file. :+1:

**Comment by MQin15** [comment]
@jenadeng Great Points! This really shows that soft skills/personalities are equally important as technical skills for software developers.

**Comment by lawsonanderson** [comment]
@jenadeng This is an excellent summary and a great resource to have for the next time I interview a developer! The picture is also totally awesome! I'm proud to give this a :+1:

**Comment by CKnaupp15** [comment]
@jenadeng This is super insightful and super well structured. Now that I saw it on your post, I also wanted to learn about the formatting which I used in my post ;)
Thanks! :+1:

**Comment by abigailcstone** [comment]
@jenadeng This is very helpful and these lessons will be some of the most valuable ones I take away from the course. One of the topics that a couple of the Y Combinator founders commented on yesterday at my event (including Olga Vidisheva, founder of Shoptiques and HBS alum) was the challenge of being the non-technical co-founder and knowing how to hire the right developer to build an mvp, or select the right CTO or technical co-founder. At the higher level of management, it seems that even if you find the right person in terms of technical capabilities it can be hard to align your visions for the companies, so communication really is key. 

Perhaps the most relevant speaker to this branch was Ruchi Sanghvi, the first female engineer at Facebook. She built the mini-feed, the largest real-time aggregator at the time, among other features, before leaving to start her own company, Cove, which was acquired by dropbox. I'll be on a mission to find the next Ruchi--she has a legendary mix of techical expertise, curiosity, sensitivity, and charisma! 

Here she is next to a screenshot of what Facebook looked like before the mini-feed (if you can remember those days!):
y combinator female founders conference 2015 ruchi sanghvi facebook
:+1:  ship away!

**Pull request merged**
